version: "3.9"

services:
  # ---------- TiDB Cluster ----------
  pd:
    image: pingcap/pd:v7.5.1
    container_name: pd
    command:
      - --name=pd
      - --data-dir=/data/pd
      - --client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://pd:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-peer-urls=http://pd:2380
      - --initial-cluster=pd=http://pd:2380
    ports:
      - "2379:2379"
    volumes:
      - pd-data:/data/pd

  tikv:
    image: pingcap/tikv:v7.5.1
    container_name: tikv
    depends_on:
      - pd
    command:
      - --pd=pd:2379
      - --addr=0.0.0.0:20160
      - --data-dir=/data/tikv
    volumes:
      - tikv-data:/data/tikv

  tidb:
    image: pingcap/tidb:v7.5.1
    container_name: tidb
    depends_on:
      - pd
      - tikv
    command:
      - --store=tikv
      - --path=pd:2379
    ports:
      - "4000:4000"

  # ---------- Kafka ----------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1

  kafka-init:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka-init
    depends_on:
      - kafka
    entrypoint: ["/bin/bash", "-lc"]
    command: >
      "
      echo 'Waiting for Kafka...';
      cub kafka-ready -b kafka:9092 1 60;
      kafka-topics --bootstrap-server kafka:9092
        --create --if-not-exists
        --topic appdb-changes
        --partitions 1
        --replication-factor 1;
      echo 'Kafka topic appdb-changes ready';
      "

  # ---------- TiDB CDC ----------
  cdc:
    image: pingcap/ticdc:v7.5.1
    container_name: ticdc
    depends_on:
      - pd
      - kafka
    command:
      - /cdc
      - server
      - --pd=http://pd:2379

  cdc-init:
    image: pingcap/ticdc:v7.5.1
    container_name: cdc-init
    depends_on:
      - cdc
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "
      echo 'Waiting for TiCDC...';
      sleep 15;
      ticdc cli changefeed create
        --pd=http://pd:2379
        --sink-uri='kafka://kafka:9092/appdb-changes';
      echo 'CDC changefeed created';
      "

  # ---------- API ----------
  api:
    build: ../api
    container_name: api
    depends_on:
      - tidb
    ports:
      - "3000:3000"

  # ---------- Consumer ----------
  consumer:
    build: ../consumer
    container_name: consumer
    depends_on:
      - kafka

volumes:
  pd-data:
  tikv-data:
